export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {

      // ✅ UPDATED — added address, nullable email
      students: {
        Row: {
          id: string
          name: string
          email: string | null
          phone: string | null
          address: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      // 🔄 REPLACED — new schema as per WTD-41
      certificates: {
        Row: {
          id: string
          certificate_id: string               // auto-generated: FMG-YYYY-NNNNN
          student_name: string
          student_email: string | null
          course_name: string
          course_description: string | null
          instructor_name: string
          duration: string                     // e.g., "2.5 total hours"
          lectures_count: number | null
          issue_date: string
          status: 'active' | 'revoked'
          reference_number: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          certificate_id?: string              // optional — auto-generated by trigger
          student_name: string
          student_email?: string | null
          course_name: string
          course_description?: string | null
          instructor_name: string
          duration: string
          lectures_count?: number | null
          issue_date: string
          status?: 'active' | 'revoked'
          reference_number?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          certificate_id?: string
          student_name?: string
          student_email?: string | null
          course_name?: string
          course_description?: string | null
          instructor_name?: string
          duration?: string
          lectures_count?: number | null
          issue_date?: string
          status?: 'active' | 'revoked'
          reference_number?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      // ➕ NEW TABLE — added as per WTD-41
      admin_users: {
        Row: {
          id: string                           // references auth.users
          email: string
          name: string
          role: 'admin' | 'super_admin'
          created_at: string
        }
        Insert: {
          id: string                           // must match auth.users id
          email: string
          name: string
          role?: 'admin' | 'super_admin'
          created_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          role?: 'admin' | 'super_admin'
          created_at?: string
        }
        Relationships: []
      }

      enquiries: {
        Row: {
          id: string
          type: 'contact' | 'partner'
          name: string
          company: string | null
          email: string
          phone: string | null
          country: string | null
          sector: string | null
          program: string | null
          message: string | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          type: 'contact' | 'partner'
          name: string
          company?: string | null
          email: string
          phone?: string | null
          country?: string | null
          sector?: string | null
          program?: string | null
          message?: string | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          type?: 'contact' | 'partner'
          name?: string
          company?: string | null
          email?: string
          phone?: string | null
          country?: string | null
          sector?: string | null
          program?: string | null
          message?: string | null
          read?: boolean
          created_at?: string
        }
        Relationships: []
      }

      // ✅ UPDATED — added requirements, salary_range, pdf_url, pdf_filename; phone replaces link
      job_listings: {
        Row: {
          id: string
          title: string
          company: string
          location: string
          description: string | null
          requirements: string | null
          salary_range: string | null
          pdf_url: string | null
          pdf_filename: string | null
          image_url: string | null
          image_filename: string | null
          contact_type: 'email' | 'whatsapp' | 'phone'
          contact_value: string
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          title: string
          company: string
          location: string
          description?: string | null
          requirements?: string | null
          salary_range?: string | null
          pdf_url?: string | null
          pdf_filename?: string | null
          image_url?: string | null
          image_filename?: string | null
          contact_type: 'email' | 'whatsapp' | 'phone'
          contact_value: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          title?: string
          company?: string
          location?: string
          description?: string | null
          requirements?: string | null
          salary_range?: string | null
          pdf_url?: string | null
          pdf_filename?: string | null
          image_url?: string | null
          image_filename?: string | null
          contact_type?: 'email' | 'whatsapp' | 'phone'
          contact_value?: string
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      // ➕ NEW — course catalog
      courses: {
        Row: {
          id: string
          name: string
          code: string
          description: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          code: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          code?: string
          description?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }

      // ➕ NEW — student enrollments
      enrollments: {
        Row: {
          id: string
          student_id: string
          course_id: string
          enrolled_at: string
          created_at: string
        }
        Insert: {
          id?: string
          student_id: string
          course_id: string
          enrolled_at: string
          created_at?: string
        }
        Update: {
          id?: string
          student_id?: string
          course_id?: string
          enrolled_at?: string
          created_at?: string
        }
        Relationships: []
      }

    }
    Views: {
      [_ in never]: never
    }

    //  NEW — generate_certificate_id function added
    Functions: {
      generate_certificate_id: {
        Args: { issue_date: string }
        Returns: string
      }
    }

    Enums: {
      certificate_status: 'active' | 'revoked'
      enquiry_status: 'new' | 'contacted' | 'closed'
      contact_type: 'whatsapp' | 'email' | 'link'
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

//  UNCHANGED helper types
export type Student = Database['public']['Tables']['students']['Row']
export type Enquiry = Database['public']['Tables']['enquiries']['Row']
export type JobListing = Database['public']['Tables']['job_listings']['Row']

//  UPDATED — now uses new certificates schema
export type Certificate = Database['public']['Tables']['certificates']['Row']

//  NEW helper type for admin_users
export type AdminUser = Database['public']['Tables']['admin_users']['Row']

// ➕ NEW — WTD-51
export type Course = Database['public']['Tables']['courses']['Row']
export type Enrollment = Database['public']['Tables']['enrollments']['Row']

// REMOVED — CertificateWithStudent no longer needed
// (student info is now stored directly in certificates table)